---
abstract: 'extremely lightweight but not very powerful web application framework'
author:
  - 'Ashley Willis <ashley+perl@gitable.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Limper
provides:
  Limper:
    file: lib/Limper.pm
    version: 0.012
  Limper::Engine:
    file: lib/Limper/Engine.pm
    version: 0.012
  Limper::Passphrase:
    file: lib/Limper/Passphrase.pm
    version: 0.012
  Limper::Plugin:
    file: lib/Limper/Plugin.pm
    version: 0.012
requires:
  Exporter: 0
  IO::Socket: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  repository: https://gitable.org/ashley/limper.git
version: 0.012
